#PUT http://localhost:8090/people/1
#Content-Type: application/json
#
#{"firstName" : "Bilbo",  "lastName" : "Baggins"}



#POST http://localhost:8090/breeds/3/species/1
#
#Content-Type: application/json
#
#{"name" : "сиба ину"}

#
#GET http://localhost:8090/people/search/a

#http://localhost:8090/people/search/findByLastName?name=Lucas

#http://localhost:8090/people

GET http://localhost:8090/people/1
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8090/species/1/breeds

###
POST http://localhost:8090/cards
Content-Type: application/json

{
  "description": "описание животного 2",
  "picture": null,
  "animal": {
    "alias": "Мурзик 2",
    "age": 5,
    "gender": 1,
    "color": "Бурый 2",
    "breed": "http://localhost:8090/breeds/2"
  },
  "address": {
    "latitude": 1,
    "longitude": 1,
    "address": "somewhere 2"
      },
  "person": "http://localhost:8090/people/1",
  "createdAt": "2012-04-23T18:25:43.511Z",
  "updatedAt": "2012-04-23T18:25:43.511Z"

}

###

GET http://localhost:8090/cards/1/person

###

GET http://localhost:8090/cards/1/comments/27

###

POST http://localhost:8090/comments
Content-Type: application/json

{
   "text": "fourth comment",
   "card": "http://localhost:8090/cards/1",
   "person": "http://localhost:8090/people/1"
}

###

POST http://localhost:8090/breeds
Content-Type: application/json

{
  "name": "test",
  "species": "http://localhost:8090/species/1"
}

###

GET http://localhost:8090/breeds/14

###