#PUT http://localhost:8090/people/1
#Content-Type: application/json
#
#{"firstName" : "Bilbo",  "lastName" : "Baggins"}



POST http://localhost:8090/breeds/3/species/1
Content-Type: application/json

{"name" : "сиба ину"}

#
#GET http://localhost:8090/people/search/a

#http://localhost:8090/people/search/findByLastName?name=Lucas

#http://localhost:8090/people

#GET http://localhost:8090/people/1


Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8090/cards/1

###


GET http://localhost:8090/species/1/breeds

###

